
# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# The hello service provides a load-balancing proxy over the hello-app
# pods. By specifying the type as a 'LoadBalancer', Kubernetes Engine will
# create an external HTTP load balancer.
apiVersion: v1
kind: Service
metadata:
  name: ks-service-b00974730
spec:
  type: LoadBalancer #remove in secnd deployment
  selector:
    app: k8s-app-b00974730
  ports:
  - port: 80
    targetPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: ks-service2-b00974730
spec:
  selector:
    app: k8s-app-b00974730
  ports:
  - port: 7002
    targetPort: 7002